// server.js

// Node.js implementation of slackline – https://github.com/ernesto-jimenez/slackline


// BASE SETUP
// ========================================================================================

// required modules
var express 	= require('express');
var app 		= express();
var bodyParser 	= require('body-parser');
var http		= require('http');
var querystring = require('querystring');
var request		= require('request');

// configure the app to use bodyParser()
// this will allow us to interpret the data from a POST
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var port = process.env.PORT || 8080;


// ROUTES
// ========================================================================================

var router = express.Router();

// test route to make sure everything is working
router.get('/', function(req, res) {
	res.json({ message: 'hooray! welcome to slackline!' });
});

router.all('/bridge', function(req, res) {
	var username = req.body.user_name;
	var text = req.body.text;
	var domain = req.query.domain;
	var token = req.query.token;

	// to avoid infinite loops, don't post messages generated by slackbot
	if (username == "slackbot") {
		console.log("don't post this message, it's from slackbot")
		return
	} else {
		sendTo(username, text, domain, token)
	};
});

app.use(router);


// START THE SERVER
// ========================================================================================

app.listen(port);
console.log('slackline is running on port ' + port);


// FUNCTIONS
// ========================================================================================

// Send a POST to the target Slack instance
function sendTo(username, text, domain, token) {

	var postURL = '/services/hooks/incoming-webhook?token='

	var options = {
		uri: 'https://' + domain + postURL + token,
		method: 'POST',
		json: {
			'username' : username,
			'text' : text,
			'icon_emoji' : ':ghost:'
		}
	};

	request(options, function(error, response, body) {
		if(!error && response.statusCode == 200) {
			console.log('Success!');
		} else {
			console.log(response);
		}
	});
};
